name: upgradeu
favicon: null
layout_spectrum: 0.8489253376610577
typography_spectrum: 0.4900831535924226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5012025767937303
  lightness: 0.3849116233177483
  saturation: 0.4714239255990833
  rhythmicContrast: 0.37024366366676986
purpose: []
